version: '{build}'

os: Visual Studio 2015

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
- nuget restore

build:
  publish_wap: true
  verbosity: minimal

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

artifacts:
- path: Erbsenzaehler.AutoImporter.Client\Bin\$(configuration)
  name: Erbsenzaehler.AutoImporter.Client
- path: Erbsenzaehler.SummaryMails.WebJob\Bin\$(configuration)
  name: Erbsenzaehler.SummaryMails.WebJob  
- path: Erbsenzaehler.AutoImporter.WebJob\Bin\$(configuration)
  name: Erbsenzaehler.AutoImporter.WebJob  

deploy:
- provider: WebDeploy
  server: http://erbsenzaehler.sachsenhofer.com/MSDEPLOYAGENTSERVICE
  website: Erbsenzaehler
  username: Administrator
  password:
    secure: 0VezCAl9nnPtt2Kdqabh3Q==
  ntlm: true
  remove_files: true
  app_offline: false
  on:
    branch: master
