version: 0.4.{build}

os: Visual Studio 2015 CTP 6

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
- nuget restore -verbosity detailed

build:
  publish_wap: true
  verbosity: minimal

configuration: Release

cache:
- packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

artifacts:
- path: Erbsenzaehler.AutoImporter.Client\Bin\$(configuration)
  name: Erbsenzaehler.AutoImporter.Client
- path: Erbsenzaehler.SummaryMails.WebJob\Bin\$(configuration)
  name: Erbsenzaehler.SummaryMails.WebJob  
- path: Erbsenzaehler.AutoImporter.WebJob\Bin\$(configuration)
  name: Erbsenzaehler.AutoImporter.WebJob  

deploy:
- provider: WebDeploy
  server: https://erbsenzaehler.scm.azurewebsites.net:443/msdeploy.axd
  website: erbsenzaehler
  username: $erbsenzaehler
  password:
    secure: ywPiOOw/o99qoQAj0OGWztq6DumwP9/7OtBCxFM1zhCkuEX2GTS8VOJl72UY66iye1iIPdnkUAxq2uPnNIauEw==
  remove_files: true
  app_offline: true
  on:
    branch: master
